#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 24 14:55:28 2026

@author: frankgallo
"""

import numpy as np
import matplotlib.pyplot as plt

pi = np.pi
rhoM = 9.117
v0 = 235.3
thetaM0 = 0.63 * pi 
mu = 29630
tf = 0.2 #t final

#Rocket positions
rocketP = np.array([1,0])
rocketV =  np.array([0,v0])


# 10k mini time slices over the 0.2 t time frame
t = np.linspace(0,tf,10000)

#moon position
def xM(t): 
    return np.array([rhoM * np.cos((2*pi*t) + thetaM0),rhoM * np.sin((2*pi*t) + thetaM0)])

# acceleration
def df2(x,t):
    #return -(mu / np.linalg.norm(x)**3) * x #used this to look for intercept
    return -(mu * x/ np.linalg.norm(x)**3) * x - ((0.0123*mu)/np.linalg.norm(x - xM(t))**3)*(x-xM(t))

#moon position
def moonPosition(t):
    x = np.zeros((len(t),2))
    
    for i in range(len(t)):
        x[i] = xM(t[i])
        
    return x

##  time integrations adapted from demo from april 13th
def ForwardEuler(t,x0,v0):
    dt = t[1] - t[0]
    
    # Create a list of 5 vectors, where each vector is a 2x2 matrix of zeros
  
    x = np.zeros((len(t),2))
    v = np.zeros((len(t),2))
    
    x[0] = x0
    v[0] = v0
    
    for i in range(len(t) - 1):
        x[i+1] = x[i] + dt*v[i]
        v[i+1] = v[i] + dt*df2(x[i],t[i])
        
    return x,v 


def SymplecticEuler(t,x0,v0):
    dt = t[1]-t[0]
    x = np.zeros((len(t),2))
    v = np.zeros((len(t),2))
    
    x[0] = x0
    v[0] = v0
    
    for i in range(len(t)-1):
        v[i+1] = v[i] + dt*df2(x[i],t[i])
        x[i+1] = x[i] + dt*v[i+1]
    
    return x,v

def VelocityVerlet(t,x0,v0):
    dt = t[1]-t[0]
    x = np.zeros((len(t),2))
    v = np.zeros((len(t),2))
    
    x[0] = x0
    v[0] = v0
    
    for i in range(len(t)-1):
        vmid = v[i] + 0.5*dt*df2(x[i],t[i])
        x[i+1] = x[i] + dt*vmid
        v[i+1] = vmid + 0.5*dt*df2(x[i+1],t[i+1])
    return x,v

#calculating for our graph
xFE, vFE = ForwardEuler(t,rocketP, rocketV) #two variables, because there are two returns from the functions
xSE, vSE = SymplecticEuler(t, rocketP, rocketV)
xVV, vVV = VelocityVerlet(t,rocketP,rocketV)
xMoon = moonPosition(t)


#note, had claude opus 4.7 and google search help with syntax for plotting

fig2,ax2 = plt.subplots()
ax2.plot(t, xFE[:, 0], label="Forward Euler")
ax2.plot(t, xSE[:, 0], label="Symplectic Euler")
ax2.plot(t, xVV[:, 0], label="Velocity Verlet")
ax2.plot(t, xMoon[:, 0], 'k--', label="Moon's orbital path")
ax2.set_xlabel("Time (t - nondimensional)")
ax2.set_ylabel("X Position(x - nondimensional)")
ax2.legend()
ax2.grid(True)


fig3,ax3 = plt.subplots()
ax3.plot(t, xFE[:, 1], label="Forward Euler")
ax3.plot(t, xSE[:, 1], label="Symplectic Euler")
ax3.plot(t, xVV[:, 1], label="Velocity Verlet")
ax3.plot(t, xMoon[:, 1], 'k--', label="Moon's orbital path")
ax3.set_xlabel("Time (t - nondimensional)")
ax3.set_ylabel("Y Position(y - nondimensional)")
ax3.legend()
ax3.grid(True)


fig1, ax1 = plt.subplots()
ax1.plot(0, 0, 'bo', label="Earth")
ax1.plot(xMoon[:, 0], xMoon[:, 1], 'k--', label="Moon's orbital path")
ax1.plot(xFE[:, 0], xFE[:, 1], label="Forward Euler")
ax1.plot(xSE[:, 0], xSE[:, 1], label="Symplectic Euler")
ax1.plot(xVV[:, 0], xVV[:, 1], label="Velocity Verlet")
ax1.set_aspect("equal")
ax1.set_xlabel("X Position(x - nondimensional)")
ax1.set_ylabel("Y Position(y - nondimensional)")
ax1.legend()
ax1.grid(True)

plt.show()

